Add psc-package support
purerl/purescript-erl-process pull request #1
Opened 2017-01-04 01:38 UTC by lostbean

This is just a small PR to update the module and add psc-package support.

2017-01-04 09:25 UTC, nwolverson requested changes
Thanks! Hope this is somehow useful to you, interested to hear any thoughts

2017-01-04 09:25 UTC, nwolverson commented on psc-package.json
> +    "set":  "erl-0.10.1",
Does this work with the latest package set? erl-0.10.2-4

2017-01-04 09:25 UTC, nwolverson commented on Makefile
> +run:
Not sure why this is renamed, isn't this running some kind of test?

2017-01-04 09:25 UTC, nwolverson commented on src/Erl/Process.purs
> +import Prelude (class Eq, Unit, eq, (<$>))
Rather keep `Prelude` imported implicitly, it is other imports which should be explicitly qualified (in this case `Control.Monad.Eff` should be

2017-01-04 23:33 UTC, lostbean commented on Makefile
> +run:
no special reason, but I agree it should be `test`

2017-01-04 23:44 UTC, lostbean commented on psc-package.json
> +    "set":  "erl-0.10.1",
Oops! I missed the new version. But it does work.

2017-01-05 00:03 UTC, lostbean commented on src/Erl/Process.purs
> +import Prelude (class Eq, Unit, eq, (<$>))
I'm also rather keep `Prelude` implicit.

Wow, I just understood  how the implicit import warning work in purescript :) Only one import is allowed to be implicit. And, in this case, makes total sense to let `Prelude` to be the one :)

2017-01-05 07:35 UTC, nwolverson approved these changes

2017-01-05 07:35 UTC, merged